version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Construire
          command: mvn -B -DskipTests clean package
      - run:
          name: Tester
          command: mvn test
      - run:
          name: Générer le rapport de couverture de code
          command: mvn jacoco:report
      - run:
          name: Vérification Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Générer le rapport HTML Checkstyle
          command: mvn checkstyle:checkstyle
      - run:
          name: Envoyer à Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  deploy-gh-pages:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Configurer Git
          command: |
            export CIRCLE_SKIP_UNCHANGED_BUILDS=false
            git config --global user.email "narutokonoya1@gmail.com"
            git config --global user.name "amadoubassceri"
      - run:
          name: Déployer sur GitHub Pages
          command: |
            git clone https://${GH_TOKEN_GITHUB}@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages
            git checkout gh-pages || git checkout -b gh-pages
            rm -rf *
            mkdir docs
            cp -r ../target/site/apidocs/* ./docs
            git add -A
            if git diff-index --quiet HEAD; then
              echo "Aucune modification à commiter"
            else
              git commit -m "Mise à jour Javadoc"
              git push https://${GH_TOKEN_GITHUB}@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages --force
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master
      - deploy-gh-pages:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
