version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout

      # Build your project and generate the Javadoc
      - run:
          name: Build and Package
          command: mvn -B -DskipTests clean package

      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Run tests and generate code coverage report
      - run:
          name: Test
          command: mvn test

      - run:
          name: Generate Code Coverage Report
          command: mvn jacoco:report

      # Run Checkstyle Verification
      - run:
          name: Run Checkstyle Verification
          command: mvn checkstyle:check

      # Generate Checkstyle HTML Report
      - run:
          name: Generate Checkstyle HTML Report
          command: mvn checkstyle:checkstyle

      # Upload to Codecov
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  deploy-gh-pages:
    docker:
      - image: cimg/python:3.8  # This is to use Python for the GitHub Pages deployment
    steps:
      - checkout

      # Install necessary dependencies for GitHub Pages deployment (git, gh-pages, etc.)
      - run:
          name: Install GitHub Pages Deploy Dependencies
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | bash -
            apt-get install -y nodejs
            npm install -g gh-pages

      # Deploy the Javadoc to GitHub Pages
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "circleci@example.com"
            git remote set-url origin https://${GH_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}.git
            gh-pages -d target/site/apidocs  # Deploy the Javadoc directory to GitHub Pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy-gh-pages:
          requires:
            - build-and-test
