version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-11  # Utilisation d'une image avec Maven et OpenJDK 11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout  # Vérifier le code source
      - run:
          name: Show Maven Test Output
          command: mvn test -X  # Exécuter les tests avec le mode debug
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report  # Générer le rapport de couverture de JaCoCo
      - run:
          name: List Coverage Report Directory
          command: ls -la target/site/jacoco  # Lister le contenu du dossier JaCoCo
      - run:
          name: List Surefire Reports
          command: ls -la target/surefire-reports  # Lister les rapports de tests Surefire

  codecov-upload:
    executor: maven-executor
    steps:
      - codecov/upload:
          token: CODECOV_TOKEN  # Utiliser le token Codecov défini dans les variables d'environnement de CircleCI
          slug: olfabre/ceri-m1-techniques-de-test  # Ajouter le slug du dépôt

workflows:
  build:
    jobs:
      - build
      - codecov-upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master  # Exécuter uniquement sur la branche master
