docs-deploy:
  docker:
    - image: cimg/openjdk:11.0
  steps:
    - checkout

    # Generate Javadoc
    - run:
        name: Generate Javadoc
        command: mvn javadoc:javadoc

    # Create docs directory if it doesn't exist
    - run:
        name: Prepare Javadoc for GitHub Pages
        command: |
          mkdir -p docs
          cp -r target/site/apidocs/* docs/

    # Create a minimal Jekyll configuration if needed
    - run:
        name: Create Jekyll configuration
        command: |
          echo "theme: jekyll-theme-minimal" > docs/_config.yml

    # Configure Git
    - run:
        name: Configure Git
        command: |
          git config --global user.email "narutokonoya1@gmail.com"
          git config --global user.name "amadoubassceri"

    # Deploy to GitHub Pages
    - run:
        name: Deploy to GitHub Pages
        command: |
          git clone https://${GH_TOKEN_GITHUB}@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages
          cd gh-pages
          git checkout gh-pages || git checkout -b gh-pages
          rm -rf *
          cp -r ../docs/* .
          git add -A
          git commit -m "[skip ci] Update Javadoc" || echo "No changes to commit"
          git push https://${GH_TOKEN_GITHUB}@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages --force