version: 2.1  # Version de la configuration CircleCI

# Importation de l'orb Codecov
orbs:
  codecov: codecov/codecov@4.0.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.4-openjdk-11

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      - run:
          name: Build and Test with Coverage
          command: mvn clean verify -DskipTests=false
      - run:
          name: Verify Coverage Report Exists
          command: |
            if [ ! -f target/site/jacoco/jacoco.xml ]; then
              echo "Error: JaCoCo coverage report not found!"
              exit 1
            fi
      - run:
          name: List Coverage Report Directory
          command: ls -la target/site/jacoco

  codecov-upload:
    executor: maven-executor
    steps:
      - checkout
      - codecov/upload:
          token: CODECOV_TOKEN
          file: "target/site/jacoco/jacoco.xml"

workflows:
  version: 2
  build:
    jobs:
      - build
      - codecov-upload:
          requires:
            - build
          filters:
            branches:
              only:
                - master
