version: 2.1

# Import the Codecov orb
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      # Checkout the code as the first step.
      - checkout

      # Build the project
      - run:
          name: Build
          command: mvn -B -DskipTests clean package

      # Run tests
      - run:
          name: Test
          command: mvn test

      # Generate the JaCoCo report
      - run:
          name: Generate Code Coverage Report
          command: mvn jacoco:report

      # Add Checkstyle verification
      - run:
          name: Run Checkstyle Verification
          command: mvn checkstyle:check

      # Generate Checkstyle HTML report
      - run:
          name: Generate Checkstyle HTML Report
          command: mvn checkstyle:checkstyle

      # Upload the coverage report to Codecov
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  docs-deploy:
    docker:
      - image: cimg/openjdk:20.0
    steps:
      - checkout

      # Generate Javadoc
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

      # Install and configure gh-pages
      - run:
          name: Install and configure gh-pages
          command: |
            # Configure git for deployment
            git config --global user.email "narutokonoya1@gmail.com"
            git config --global user.name "amadoubassceri"

            # Clone the repository and switch to gh-pages branch
            git clone https://$TOKEN_JAVADOC@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages
            cd gh-pages

            # Checkout gh-pages branch or create it if it doesn't exist
            git checkout gh-pages || git checkout -b gh-pages

            # Pull latest changes from the gh-pages branch
            git pull origin gh-pages --rebase || echo "No remote changes to pull"

            # Copy all Javadoc files into the root of the gh-pages branch
            cp -r ../target/site/apidocs/* ./

            # Add, commit, and push changes to GitHub Pages
            git add -A
            git commit -m "[skip ci] Updated Javadoc" || echo "No changes to commit"
            git push https://$TOKEN_JAVADOC@github.com/amadoubassceri/ceri-m1-techniques-de-test.git gh-pages --force

# Define workflows to manage job execution
workflows:
  version: 2
  sample-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      - docs-deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
